--liquibase formatted sql

--changeset dongfangchao:1
ALTER TABLE `per_insurance_info` MODIFY COLUMN `STORE_NAME`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '店铺名称';

--changeset dongfangchao:2
UPDATE vehicle_ins_detail SET SRC_BIZ_PREMIUM_INTERVAL = 3474350, SRC_COMPEL_PREMIUM_INTERVAL = 770000, SRC_TAX_PREIMUM = 720000 WHERE PER_INSURANCE_ORDER_NO = '102050389415295066';

--changeset dongfangchao:201705221736
UPDATE per_insurance_info SET PRODUCT_NAME = '店铺保' WHERE PRODUCT_ID = 'S01001' AND PRODUCT_NAME = '财产险';

--changeset dongfangchao:201706150905
ALTER TABLE `per_insurance_info` ADD COLUMN `ORDER_STATUS_CAUSE`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `ORDER_STATUS`;

CREATE TABLE `pingan_insured_grade` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSURED_GRADE_CODE` varchar(255) DEFAULT NULL COMMENT '保额档次CODE',
  `INSURED_AMOUNT` varchar(255) DEFAULT NULL COMMENT '保额',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='平安保额和保额CODE映射表';

CREATE TABLE `pingan_region` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGION_NAME` varchar(255) DEFAULT NULL,
  `GB_CODE` varchar(255) DEFAULT NULL,
  `PARENT` int(11) DEFAULT NULL,
  `TREE_PATH` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='平安地址库';

CREATE TABLE `pingan_typhoon_control_region` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REGION_ID` int(11) DEFAULT NULL COMMENT '地区ID',
  `REGION_NAME` varchar(255) DEFAULT NULL COMMENT '地区名称',
  `TREE_PATH` varchar(255) DEFAULT NULL COMMENT '地区路径',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uindex` (`REGION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='平安台风控制区表';

CREATE TABLE `pre_order_user_info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PER_INSURANCE_ORDER_NO` varchar(255) DEFAULT NULL COMMENT '金服订单号',
  `TOBACCO_CERTIFICATE_NO` varchar(255) DEFAULT NULL COMMENT '烟草证号',
  `STORE_NAME` varchar(255) DEFAULT NULL COMMENT '店铺名',
  `USER_NAME` varchar(255) DEFAULT NULL COMMENT '客户名称',
  `ID_CARD_NO` varchar(255) DEFAULT NULL COMMENT '身份证号',
  `LINKMAN_NAME` varchar(255) DEFAULT NULL COMMENT '联系人名称',
  `MOBILE` varchar(255) DEFAULT NULL COMMENT '手机号',
  `PROVINCE_GB_CODE` varchar(255) DEFAULT NULL COMMENT '省份国标码',
  `PROVINCE_ID` int(11) DEFAULT NULL COMMENT '省份ID',
  `PROVINCE_NAME` varchar(255) DEFAULT NULL COMMENT '省份名称',
  `CITY_GB_CODE` varchar(255) DEFAULT NULL COMMENT '城市国标码',
  `CITY_ID` int(11) DEFAULT NULL COMMENT '城市ID',
  `CITY_NAME` varchar(255) DEFAULT NULL COMMENT '城市名称',
  `COUNTY_GB_CODE` varchar(255) DEFAULT NULL COMMENT '区县国标码',
  `COUNTY_ID` int(11) DEFAULT NULL COMMENT '区县ID',
  `COUNTY_NAME` varchar(255) DEFAULT NULL COMMENT '区县名称',
  `DETAIL_ADDRESS` varchar(255) DEFAULT NULL COMMENT '详细地址',
  `EMAIL` varchar(255) DEFAULT NULL COMMENT '电子邮箱',
  `INSURANCE_BEGIN_DATE` datetime DEFAULT NULL COMMENT '保险起期',
  `PRODUCT_CODE` varchar(255) DEFAULT NULL COMMENT '平安的产品编码',
  `PLAN_CODE` varchar(255) DEFAULT NULL COMMENT '险种编码',
  `APPLY_POLICY_NO` varchar(255) DEFAULT NULL COMMENT '投保单号',
  `POLICY_NO` varchar(255) DEFAULT NULL COMMENT '保单号',
  `TOTAL_INSURED_AMOUNT` double(16,2) DEFAULT NULL COMMENT '保额',
  `TOTAL_ACTUAL_PREIUM` double(16,2) DEFAULT NULL COMMENT '保费',
  `CREATE_OPID` varchar(20) DEFAULT NULL COMMENT '创建人',
  `CREATE_TS` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `LAST_MNT_OPID` varchar(20) DEFAULT NULL COMMENT '最后修改人',
  `LAST_MNT_TS` datetime(6) DEFAULT NULL COMMENT '最后修改时间',
  `VERSION_CT` decimal(17,0) DEFAULT '0' COMMENT '版本号',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `trans_history` (
  `TRANS_SERIAL_NO` varchar(255) NOT NULL COMMENT '交易流水号',
  `REQUEST_URL` varchar(255) DEFAULT NULL,
  `TRANS_TYPE` varchar(255) DEFAULT NULL COMMENT '交易类型',
  `TRANS_REQUEST` varchar(255) DEFAULT NULL COMMENT '请求体',
  `TRANS_RESPONSE` varchar(255) DEFAULT NULL COMMENT '响应',
  `CREATE_OPID` varchar(20) DEFAULT NULL COMMENT '创建人',
  `CREATE_TS` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `LAST_MNT_OPID` varchar(20) DEFAULT NULL COMMENT '最后修改人',
  `LAST_MNT_TS` datetime(6) DEFAULT NULL COMMENT '最后修改时间',
  `VERSION_CT` decimal(17,0) DEFAULT '0' COMMENT '版本号',
  PRIMARY KEY (`TRANS_SERIAL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='请求记录表';

--changeset dongfangchao:201706151621
ALTER TABLE `pre_order_user_info` ADD COLUMN `STORE_ID`  bigint(20) NULL AFTER `TOBACCO_CERTIFICATE_NO`;

--changeset dongfangchao:201707101053
ALTER TABLE `trans_history`
MODIFY COLUMN `TRANS_REQUEST`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '请求体' AFTER `TRANS_TYPE`,
MODIFY COLUMN `TRANS_RESPONSE`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '响应' AFTER `TRANS_REQUEST`;

--changeset dongfangchao:201707111554
ALTER TABLE `trans_history`
ADD COLUMN `ORDER_NO`  varchar(255) NULL COMMENT '订单号' AFTER `TRANS_SERIAL_NO`;

--changeset dongfangchao:201707111733
ALTER TABLE `pre_order_user_info`
ADD COLUMN `POLICY_FILE_DOWNLOADED`  tinyint(1) NULL COMMENT '是否已下载保单文件' AFTER `TOTAL_ACTUAL_PREIUM`;

--changeset dongfangchao:201707121608
ALTER TABLE `pre_order_user_info`
ADD COLUMN `INSURED_GRADE_CODE`  varchar(255) NULL COMMENT '保额等级CODE' AFTER `POLICY_FILE_DOWNLOADED`;